basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('summary/', views.basket_summary, name='basket_summary'),
    path('summary/add/', views.basket_add, name='basket_add'),
    path('summary/delete/', views.basket_delete, name='basket_delete'),
    path('summary/update/', views.basket_update, name='basket_update'),
]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slag>/', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/minion.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

basket/forms.py
from django import forms


class BasketAddProductForm(forms.Form):
    qty = forms.IntegerField(min_value=1)

basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from store.models import Product
from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

store/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def products_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})


def category_list(request, category_slag):
    category_req = get_object_or_404(Category, slug=category_slag)
    prods_from_category = Product.products.filter(category=category_req)
    return render(request, 'store/products/category.html', {'category': category_req, 'products': prods_from_category})

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %} Basket Summary{% endblock %}
{% block content %}

    <main class="pt-5">
        <div class="container">
            <h1 class="h5">Shopping basket</h1>
            {% for item in basket %}
                {% with product=item.product %}
                    <div data-index="{{ product.id }}" class="row g-3 product-item">
                        <div class="col-md-5 col-lg-5 order-md-first">
                            <img class="img-fluid mx-auto d-block" src="{{ product.image.url }}" alt="Responsive image">
                        </div>
                        <div class="p-4 mb-4 bg-light rounded-3 col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                            <h1 class="mb-2 h4">{{ product.title }}</h1>
                            <p>{{ product.description|slice:"255" }}</p>
                            <hr class="my-4">
                            <div>
                                <div class="row p-3">
                                    <div class="col-6">Hardback</div>
                                    <div class="col-6 text-end"><span class="h5 fw-bold">${{ item.total_price }}</span>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4">

                            <div class="d-flex flex-wrap justify-content-between align-items-center">
                                <div class="col-2 d-flex flex-column flex-md-row align-items-center">
                                    <label for="select">Qty</label>
                                    <select id="select {{product.id}}">
                                        <option value="">{{ item.qty }}</option>
                                        <option value="">1</option>
                                        <option value="">2</option>
                                        <option value="">3</option>
                                        <option value="">4</option>
                                    </select>
                                </div>


                                <div class="btn-group col-md-4 justify-content-end" role="group"
                                     aria-label="Basic outlined example">
                                    <button type="button" id="delete-button" data-index="{{product.id}}"
                                            class="btn btn-outline-primary btn-sm delete-button">Delete
                                    </button>
                                    <button type="button" id="update-button" data-index="{{product.id}}"
                                            class="btn btn-outline-primary btn-sm update-button">Update
                                    </button>
                                </div>

                            </div>
                        </div>
                        <hr class="my-4">
                    </div>
                {% endwith %}
            {% endfor %}
            <div class="col-12 text-end">
                <div class="h4 fw-bold">Sub Total: $
                    <span id="subtotal" class="d-inline-flex">{{ basket.get_total_price }}</span>
                </div>
            </div>
            <hr class="my-4">
        </div>
    </main>
    <script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on("click", ".update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data("index"),
        productqty: $("#select" + prodid + " option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post"
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}