account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='store/account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    # Register
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="store/account/user/delete_confirm.html"),
         name='delete_confirmation'),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('summary/', views.basket_summary, name='basket_summary'),
    path('summary/add/', views.basket_add, name='basket_add'),
    path('summary/delete/', views.basket_delete, name='basket_delete'),
    path('summary/update/', views.basket_update, name='basket_update'),
]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slag>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/minion.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def products_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})


def category_list(request, category_slag):
    category_req = get_object_or_404(Category, slug=category_slag)
    prods_from_category = Product.products.filter(category=category_req)
    return render(request, 'store/products/category.html', {'category': category_req, 'products': prods_from_category})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} My shop {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
</head>
<body>
<header class="p-3 bg-light text-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-lg-start">
            <a href="{% url "store:products_all" %}" class="navbar-brand">MyStore</a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 mb-md-0">
                <li><a href="#" id="navbarDropdown" class="nav-link dropdown-toggle px-2 text-dark" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                    Category
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url "store:products_all" %}">All</a></li>
                        {% for each_c in categories %}
                            <li><a class="dropdown-item"
                                   href="{{ each_c.get_absolute_url }}">{{ each_c.name|title }}</a>
                            </li>
                        {% endfor %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
{#            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">#}
{#                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">#}
{#            </form>#}
                <form class="d-flex w-100 d-md-none">
                    <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                           aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>

            <div class="text-end">
                {% if user.is_authenticated %}
                    <a type="button" role="button" href="{% url "account:logout" %}"
                       class="btn btn-outline-primary me-2">
                        <span>Logout</span>
                    </a>
                {% else %}
                    <a type="button" role="button" href="{% url "account:login" %}"
                       class="btn btn-outline-primary me-2">
                        <span>Login</span>
                    </a>
                {% endif %}
                <a type="button" role="button" href="{% url "basket:basket_summary" %}" class="btn btn-primary">
                    Basket
                    {% with total_qty=basket|length %}
                        <span id="basket-qty" class="badge badge-light">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            </span>
                    {% endwith %}

                    <span class="sr-only">items</span>
                </a>
            </div>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

</body>
</html>

templates/store/home.html
{% extends './base.html' %}
{% load static %}
{% block title %} MyStore {% endblock %}
{% block content %}
    <section class="py-2 text-center container">
        <div class="row py-lg-2">
            <div class="col-lg-10 col-md-8 mx-auto">
                <h1 class="fw-light">All Products</h1>
                <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium culpa
                    nostrum obcaecati soluta voluptate voluptatibus!</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Main call to action</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">All Products</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{{ product.image.url }}" alt="Responsive image" class="img-fluid">
                            <div class="card-body">
                                <p class="card-text">
                                    <a href="{{ product.get_absolute_url }}"
                                       class="dark-text text-decoration-none">{{ product.title }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">5min read</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}