basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('summary/', views.basket_summary, name='basket_summary'),
    path('summary/add/', views.basket_add, name='basket_add'),
    path('summary/delete/', views.basket_delete, name='basket_delete'),
    path('summary/update/', views.basket_update, name='basket_update'),
]

eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slag>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/minion.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def products_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})


def category_list(request, category_slag):
    category_req = get_object_or_404(Category, slug=category_slag)
    prods_from_category = Product.products.filter(category=category_req)
    return render(request, 'store/products/category.html', {'category': category_req, 'products': prods_from_category})

templates/store/products/category.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Home page {% endblock %}
{% block content %}
{#    <section class="py-5 text-center container">#}
{#        <div class="row py-lg-5">#}
{#            <div class="col-lg-6 col-md-8 mx-auto">#}
{#                <h1 class="fw-light">{{ category.name|title }}</h1>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">{{ category }}</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{{ product.image.url }}" alt="Responsive image" class="img-fluid">
                            <div class="card-body">
                                <p class="card-text">
                                    <a href="{{ product.get_absolute_url }}"
                                       class="dark-text text-decoration-none">{{ product.title }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">5min read</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/store/products/single.html
{% extends "../base.html" %}
{% load static %}
{% block title %} Product detail page {% endblock %}
{% block content %}
    <div class="container">
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first">
                    <img class="img-fluid mx-auto d-block" src="{{ product.image.url }}" alt="Responsive image">
                </div>
                <div class="p-5 mb-4 bg-light rounded-3 col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ product.title }}</h1>
                    <p><span class="lead">{{ product.author }}</span>(Author)</p>
                    <p>{{ product.description|slice:"255" }}</p>
                    <hr class="my-4">
                    <div>
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">${{ product.price }}</span></div>
                        </div>
                    </div>
                    <hr class="my-4">

                    <div class="d-flex flex-md-row align-items-center p-3 box-shadow">
                        <div class="col-2 d-flex flex-column flex-md-row align-items-center">
                            <label for="select">Qty</label>
                            <select id="select">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                        <div class="col-10 text-end">
                            <button type="button" id="add-button" value="{{ product.id }}"
                                    class="btn btn-primary btn-block btn-lg float-end">
                                <i class="fas fa-cart-plus"></i> Add
                            </button>
                        </div>

                    </div>
                </div>

                <hr class="my-4">
                <h5>Star rating </h5>
                <div class="rating"><input type="radio" name="rating" value="5" id="5">
                    <label for="5">☆</label> <input type="radio" name="rating" value="4" id="4">
                    <label for="4">☆</label> <input type="radio" name="rating" value="3" id="3">
                    <label for="3">☆</label> <input type="radio" name="rating" value="2" id="2">
                    <label for="2">☆</label> <input type="radio" name="rating" value="1" id="1">
                    <label for="1">☆</label>
                </div>
            </div>
        </main>
    </div>

    <script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("basket-qty").innerHTML = json.qty
                },
                error: function (xhr, errmsg, err) {
                }
            });
        })
    </script>
{% endblock %}